version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  lint-build-test-deploy:
    jobs:
      - lint-code
      - build-and-test:
          requires:
            - lint-code
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          app-name: $HEROKU_APP_NAME
          requires:
            - build-and-test
          filters:
            branches:
              only: main

jobs:
  lint-code:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm'

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: install dependencies
          command: sudo npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: lint check
          command: npm run format:check

  build-and-test:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm'

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: install dependencies
          command: sudo npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: run tests
          command: npm test -- --coverage

      - run:
          name: artifacts fix
          command: |
            RESULTS_DIR=`ls -d coverage*`
            mkdir coverage
            cp -r $RESULTS_DIR/ coverage

      - store_artifacts:
          path: coverage
