name: Create badges

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Get Coverage for badge
        run: |
          LINES_SUMMARY="$(npm test -- --coverageReporters='text-summary' | tail -2 | head -1)"
          FUNCTIONS_SUMMARY="$(npm test -- --coverageReporters='text-summary' | tail -3 | head -1)"
          LINES_TOKENS=($LINES_SUMMARY)
          FUNCTIONS_TOKENS=($FUNCTIONS_SUMMARY)
          
          echo "LINES_COVERAGE=$(echo ${LINES_TOKENS[2]})" >> $GITHUB_ENV
          echo "FUNCTIONS_COVERAGE=$(echo ${FUNCTIONS_TOKENS[2]})" >> $GITHUB_ENV

      - name: Dynamic Badges
        uses: Schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ff6b0a9c2533fb95012faa87fe9d4591
          filename: functions-badge.json
          label: coverage:functions
          message: ${{ env.FUNCTIONS_COVERAGE }}
          color: green
          
      - name: Dynamic Badges
        uses: Schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 0b893e77a446f764d9d9e90b7566647e
          filename: lines-badge.json
          label: coverage:lines
          message: ${{ env.LINES_COVERAGE }}
          color: green
